In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT / "src"))

In [2]:
import step2_lightgbm_2y as forecaster

In [1]:
print("hello")

hello

In [ ]:
import sqlite3
import pandas as pd

db_path = ""

conn = sqlite3.connect(db_path)

query = """
SELECT *
FROM traffic_counts
WHERE Start_Time >= datetime('now', '-3 years');
"""

df = pd.read_sql_query(query, conn)
conn.close()
df

:

:

In [ ]:
import sqlite3
import pandas as pd

db_path = ""

conn = sqlite3.connect(db_path)

query = """
SELECT *
FROM traffic_counts
WHERE Start_Time >= datetime('now', '-3 years');
"""

df = pd.read_sql_query(query, conn)
conn.close()
df

,Site_ID,Direction,Modus,Start_Time,End_Time,Count
0,Location_Tag_1,IN,FIETSERS,2023-05-17 20:30:00.0,2023-05-17 20:45:00.0,3.0
1,Location_Tag_1,IN,FIETSERS,2023-05-17 20:45:00.0,2023-05-17 21:00:00.0,1.0
2,Location_Tag_1,IN,FIETSERS,2023-05-17 21:00:00.0,2023-05-17 21:15:00.0,3.0
3,Location_Tag_1,IN,FIETSERS,2023-05-17 21:15:00.0,2023-05-17 21:30:00.0,2.0
4,Location_Tag_1,IN,FIETSERS,2023-05-17 21:30:00.0,2023-05-17 21:45:00.0,1.0
...,...,...,...,...,...,...
29330645,Location_Tag_152,OUT,FIETSERS,2026-05-13 03:45:00.0,2026-05-13 04:00:00.0,0.0
29330646,Location_Tag_152,OUT,FIETSERS,2026-05-13 04:00:00.0,2026-05-13 04:15:00.0,0.0
29330647,Location_Tag_152,OUT,FIETSERS,2026-05-13 04:15:00.0,2026-05-13 04:30:00.0,0.0
29330648,Location_Tag_152,OUT,FIETSERS,2026-05-13 04:30:00.0,2026-05-13 04:45:00.0,0.0
29330649,Location_Tag_152,OUT,FIETSERS,2026-05-13 04:45:00.0,2026-05-13 05:00:00.0,0.0

In [ ]:
import sqlite3
import pandas as pd

db_path = ""

conn = sqlite3.connect(db_path)

query = """
SELECT * FROM traffic_counts 
WHERE Start_Time >= '2023-09-01 00:00:00' 
AND End_Time <= '2023-09-30 23:59:59';
"""

df = pd.read_sql_query(query, conn)
conn.close()
df

,Site_ID,Direction,Modus,Start_Time,End_Time,Count
0,Location_Tag_1,IN,FIETSERS,2023-09-01 00:00:00.0,2023-09-01 00:15:00.0,0.0
1,Location_Tag_1,IN,FIETSERS,2023-09-01 00:15:00.0,2023-09-01 00:30:00.0,0.0
2,Location_Tag_1,IN,FIETSERS,2023-09-01 00:30:00.0,2023-09-01 00:45:00.0,1.0
3,Location_Tag_1,IN,FIETSERS,2023-09-01 00:45:00.0,2023-09-01 01:00:00.0,0.0
4,Location_Tag_1,IN,FIETSERS,2023-09-01 01:00:00.0,2023-09-01 01:15:00.0,0.0
...,...,...,...,...,...,...
795911,Location_Tag_143,OUT,FIETSERS,2023-09-30 22:30:00.0,2023-09-30 22:45:00.0,14.0
795912,Location_Tag_143,OUT,FIETSERS,2023-09-30 22:45:00.0,2023-09-30 23:00:00.0,21.0
795913,Location_Tag_143,OUT,FIETSERS,2023-09-30 23:00:00.0,2023-09-30 23:15:00.0,20.0
795914,Location_Tag_143,OUT,FIETSERS,2023-09-30 23:15:00.0,2023-09-30 23:30:00.0,15.0
795915,Location_Tag_143,OUT,FIETSERS,2023-09-30 23:30:00.0,2023-09-30 23:45:00.0,16.0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Site_ID     5 non-null      str
 1   Direction   5 non-null      str
 2   Modus       5 non-null      str
 3   Start_Time  5 non-null      str
 4   End_Time    5 non-null      str
 5   Count       5 non-null      float64
dtypes: float64(1), str(5)
memory usage: 702.0 bytes

In [ ]:
forecaster.run_pipeline(
    db_path="",
    cutoff= "2020-10-01",
    forecast_end="2021-04-01"
)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000419 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1855
[LightGBM] [Info] Number of data points in the train set: 9611, number of used features: 13
[LightGBM] [Info] Start training from score 405.653314
Recursive LightGBM MAE: 106.71846047899645
Recursive LightGBM RMSE: 152.56749924972243

{'df_daily':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 0      Location_Tag_1 2019-08-01  495.0          3      8        213
 1      Location_Tag_1 2019-08-02  364.0          4      8        214
 2      Location_Tag_1 2019-08-03  273.0          5      8        215
 3      Location_Tag_1 2019-08-04  424.0          6      8        216
 4      Location_Tag_1 2019-08-05  455.0          0      8        217
 ...               ...        ...    ...        ...    ...        ...
 15581  Location_Tag_9 2021-04-26  423.0          0      4        116
 15582  Location_Tag_9 2021-04-27  456.0          1      4        117
 15583  Location_Tag_9 2021-04-28  496.0          2      4        118
 15584  Location_Tag_9 2021-04-29  322.0          3      4        119
 15585  Location_Tag_9 2021-04-30  337.0          4      4        120

        is_weekend  month_sin  month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 0               0  -0.866025       -0.5 -0.501242 -0.865307    NaN    NaN
 1               0  -0.866025       -0.5 -0.516062 -0.856551  495.0    NaN
 2               1  -0.866025       -0.5 -0.530730 -0.847541  364.0    NaN
 3               1  -0.866025       -0.5 -0.545240 -0.838280  273.0    NaN
 4               0  -0.866025       -0.5 -0.559589 -0.828770  424.0    NaN
 ...           ...        ...        ...       ...       ...    ...    ...
 15581           0   0.866025       -0.5  0.910605 -0.413279  226.0  330.0
 15582           0   0.866025       -0.5  0.903356 -0.428892  423.0  444.0
 15583           0   0.866025       -0.5  0.895839 -0.444378  456.0  452.0
 15584           0   0.866025       -0.5  0.888057 -0.459733  496.0  372.0
 15585           0   0.866025       -0.5  0.880012 -0.474951  322.0  395.0

        lag_14  lag_28
 0         NaN     NaN
 1         NaN     NaN
 2         NaN     NaN
 3         NaN     NaN
 4         NaN     NaN
 ...       ...     ...
 15581   159.0   394.0
 15582   219.0   407.0
 15583   201.0   432.0
 15584   197.0   361.0
 15585   253.0   208.0

 [15586 rows x 15 columns],
 'df_model':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 28     Location_Tag_1 2019-08-29  499.0          3      8        241
 29     Location_Tag_1 2019-08-30  483.0          4      8        242
 30     Location_Tag_1 2019-08-31  292.0          5      8        243
 31     Location_Tag_1 2019-09-01  818.0          6      9        244
 32     Location_Tag_1 2019-09-02  537.0          0      9        245
 ...               ...        ...    ...        ...    ...        ...
 15581  Location_Tag_9 2021-04-26  423.0          0      4        116
 15582  Location_Tag_9 2021-04-27  456.0          1      4        117
 15583  Location_Tag_9 2021-04-28  496.0          2      4        118
 15584  Location_Tag_9 2021-04-29  322.0          3      4        119
 15585  Location_Tag_9 2021-04-30  337.0          4      4        120

        is_weekend  month_sin     month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 28              0  -0.866025 -5.000000e-01 -0.845249 -0.534373  472.0  501.0
 29              0  -0.866025 -5.000000e-01 -0.854322 -0.519744  499.0  431.0
 30              1  -0.866025 -5.000000e-01 -0.863142 -0.504961  483.0  263.0
 31              1  -1.000000 -1.836970e-16 -0.871706 -0.490029  292.0  382.0
 32              0  -1.000000 -1.836970e-16 -0.880012 -0.474951  818.0  546.0
 ...           ...        ...           ...       ...       ...    ...    ...
 15581           0   0.866025 -5.000000e-01  0.910605 -0.413279  226.0  330.0
 15582           0   0.866025 -5.000000e-01  0.903356 -0.428892  423.0  444.0
 15583           0   0.866025 -5.000000e-01  0.895839 -0.444378  456.0  452.0
 15584           0   0.866025 -5.000000e-01  0.888057 -0.459733  496.0  372.0
 15585           0   0.866025 -5.000000e-01  0.880012 -0.474951  322.0  395.0

        lag_14  lag_28
 28      237.0   495.0
 29      291.0   364.0
 30       96.0   273.0
 31      151.0   424.0
 32      363.0   455.0
 ...       ...     ...
 15581   159.0   394.0
 15582   219.0   407.0
 15583   201.0   432.0
 15584   197.0   361.0
 15585   253.0   208.0

 [14886 rows x 15 columns],
 'train_2Y':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 28     Location_Tag_1 2019-08-29  499.0          3      8        241
 29     Location_Tag_1 2019-08-30  483.0          4      8        242
 30     Location_Tag_1 2019-08-31  292.0          5      8        243
 31     Location_Tag_1 2019-09-01  818.0          6      9        244
 32     Location_Tag_1 2019-09-02  537.0          0      9        245
 ...               ...        ...    ...        ...    ...        ...
 15370  Location_Tag_9 2020-09-27  129.0          6      9        271
 15371  Location_Tag_9 2020-09-28  230.0          0      9        272
 15372  Location_Tag_9 2020-09-29  445.0          1      9        273
 15373  Location_Tag_9 2020-09-30  472.0          2      9        274
 15374  Location_Tag_9 2020-10-01  326.0          3     10        275

        is_weekend  month_sin     month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 28              0  -0.866025 -5.000000e-01 -0.845249 -0.534373  472.0  501.0
 29              0  -0.866025 -5.000000e-01 -0.854322 -0.519744  499.0  431.0
 30              1  -0.866025 -5.000000e-01 -0.863142 -0.504961  483.0  263.0
 31              1  -1.000000 -1.836970e-16 -0.871706 -0.490029  292.0  382.0
 32              0  -1.000000 -1.836970e-16 -0.880012 -0.474951  818.0  546.0
 ...           ...        ...           ...       ...       ...    ...    ...
 15370           1  -1.000000 -1.836970e-16 -0.998880 -0.047321  112.0  404.0
 15371           0  -1.000000 -1.836970e-16 -0.999546 -0.030120  129.0  606.0
 15372           0  -1.000000 -1.836970e-16 -0.999917 -0.012910  230.0  641.0
 15373           0  -1.000000 -1.836970e-16 -0.999991  0.004304  445.0  523.0
 15374           0  -0.866025  5.000000e-01 -0.999769  0.021516  472.0  406.0

        lag_14  lag_28
 28      237.0   495.0
 29      291.0   364.0
 30       96.0   273.0
 31      151.0   424.0
 32      363.0   455.0
 ...       ...     ...
 15370   434.0   148.0
 15371   642.0   322.0
 15372   600.0   589.0
 15373   642.0   636.0
 15374   541.0   402.0

 [9611 rows x 15 columns],
 'test_actual_2Y':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 428    Location_Tag_1 2020-10-02  284.0          4     10        276
 429    Location_Tag_1 2020-10-03  137.0          5     10        277
 430    Location_Tag_1 2020-10-04  176.0          6     10        278
 431    Location_Tag_1 2020-10-05  272.0          0     10        279
 432    Location_Tag_1 2020-10-06  365.0          1     10        280
 ...               ...        ...    ...        ...    ...        ...
 15552  Location_Tag_9 2021-03-28  186.0          6      3         87
 15553  Location_Tag_9 2021-03-29  394.0          0      3         88
 15554  Location_Tag_9 2021-03-30  407.0          1      3         89
 15555  Location_Tag_9 2021-03-31  432.0          2      3         90
 15556  Location_Tag_9 2021-04-01  361.0          3      4         91

        is_weekend  month_sin     month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 428             0  -0.866025  5.000000e-01 -0.999250  0.038722  295.0  281.0
 429             1  -0.866025  5.000000e-01 -0.998435  0.055917  284.0   80.0
 430             1  -0.866025  5.000000e-01 -0.997325  0.073095  137.0  168.0
 431             0  -0.866025  5.000000e-01 -0.995919  0.090252  176.0  258.0
 432             0  -0.866025  5.000000e-01 -0.994218  0.107381  272.0  505.0
 ...           ...        ...           ...       ...       ...    ...    ...
 15552           1   1.000000  6.123234e-17  0.997325  0.073095  131.0  148.0
 15553           0   1.000000  6.123234e-17  0.998435  0.055917  186.0  313.0
 15554           0   1.000000  6.123234e-17  0.999250  0.038722  394.0  374.0
 15555           0   1.000000  6.123234e-17  0.999769  0.021516  407.0  399.0
 15556           0   0.866025 -5.000000e-01  0.999991  0.004304  432.0  325.0

        lag_14  lag_28
 428     603.0   442.0
 429     387.0   329.0
 430     777.0   594.0
 431     596.0   582.0
 432     645.0   616.0
 ...       ...     ...
 15552    89.0   258.0
 15553   257.0   343.0
 15554   222.0   451.0
 15555   246.0   422.0
 15556   289.0   210.0

 [4550 rows x 15 columns],
 'lgbm_model_2Y': LGBMRegressor(learning_rate=0.05, n_estimators=500, random_state=42),
 'eval_df_2Y':               Site_ID Start_Time  dayofweek  month  dayofyear  is_weekend  \
 0      Location_Tag_1 2020-10-02          4     10        276           0
 1     Location_Tag_10 2020-10-02          4     10        276           0
 2     Location_Tag_11 2020-10-02          4     10        276           0
 3     Location_Tag_12 2020-10-02          4     10        276           0
 4     Location_Tag_13 2020-10-02          4     10        276           0
 ...               ...        ...        ...    ...        ...         ...
 4545   Location_Tag_5 2021-04-01          3      4         91           0
 4546   Location_Tag_6 2021-04-01          3      4         91           0
 4547   Location_Tag_7 2021-04-01          3      4         91           0
 4548   Location_Tag_8 2021-04-01          3      4         91           0
 4549   Location_Tag_9 2021-04-01          3      4         91           0

       month_sin  month_cos   doy_sin   doy_cos       lag_1       lag_7  \
 0     -0.866025        0.5 -0.999250  0.038722  295.000000  281.000000
 1     -0.866025        0.5 -0.999250  0.038722  173.000000  212.000000
 2     -0.866025        0.5 -0.999250  0.038722  232.000000  274.000000
 3     -0.866025        0.5 -0.999250  0.038722  252.000000  228.000000
 4     -0.866025        0.5 -0.999250  0.038722  676.000000  597.000000
 ...         ...        ...       ...       ...         ...         ...
 4545   0.866025       -0.5  0.999991  0.004304   96.848991  134.700476
 4546   0.866025       -0.5  0.999991  0.004304  201.415713  287.061845
 4547   0.866025       -0.5  0.999991  0.004304  191.545659  234.775376
 4548   0.866025       -0.5  0.999991  0.004304  170.701544  212.404664
 4549   0.866025       -0.5  0.999991  0.004304  218.278445  303.562889

            lag_14      lag_28        pred  actual
 0      603.000000  442.000000  347.952145   284.0
 1      403.000000  367.000000  242.120192   143.0
 2      596.000000  538.000000  357.514684   237.0
 3      467.000000  301.000000  294.586187   177.0
 4     1047.000000  903.000000  733.016804   660.0
 ...           ...         ...         ...     ...
 4545   134.768768   95.008877  140.841782   203.0
 4546   295.185342  285.432148  245.949068   332.0
 4547   273.073695  265.042878  228.602047   297.0
 4548   250.187193  246.378808  201.965801   258.0
 4549   296.788775  290.094134  278.219471   361.0

 [4550 rows x 16 columns]}