In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT / "src"))

In [2]:
import step2_lightgbm_2y as forecaster

/Users/wingong/miniconda3/envs/py312/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
forecaster.main()

Set params: cutoff=None, forecast_end=None, train_days=None
Set params: args.cutoff=None, args.forecast_end=/Users/wingong/Library/Jupyter/runtime/kernel-v3a3b9cbce85f12a494f2784548b6487afe9fde3fe.json, args.train_days=None

In [9]:
db_path = "/Users/wingong/Library/Mobile Documents/com~apple~CloudDocs/Statistics Study/G0Z39B Modern Data Analytics/mda-cycling/data/fietstellingen.db"

In [10]:
forecaster.load_raw_data(db_path=db_path, cutoff="2026-04-01", forecast_end="2026-04-30", days=10)

query:
    SELECT *
    FROM "traffic_counts"
    WHERE Start_Time >= "2026-03-22 00:00:00"
    AND End_Time <= "2026-04-30 23:59:59";

,Site_ID,Direction,Modus,Start_Time,End_Time,Count
0,Location_Tag_1,IN,FIETSERS,2026-03-22 00:00:00.0,2026-03-22 00:15:00.0,0.0
1,Location_Tag_1,IN,FIETSERS,2026-03-22 00:15:00.0,2026-03-22 00:30:00.0,0.0
2,Location_Tag_1,IN,FIETSERS,2026-03-22 00:30:00.0,2026-03-22 00:45:00.0,0.0
3,Location_Tag_1,IN,FIETSERS,2026-03-22 00:45:00.0,2026-03-22 01:00:00.0,0.0
4,Location_Tag_1,IN,FIETSERS,2026-03-22 01:00:00.0,2026-03-22 01:15:00.0,0.0
...,...,...,...,...,...,...
1107937,Location_Tag_152,OUT,FIETSERS,2026-04-30 22:30:00.0,2026-04-30 22:45:00.0,0.0
1107938,Location_Tag_152,OUT,FIETSERS,2026-04-30 22:45:00.0,2026-04-30 23:00:00.0,0.0
1107939,Location_Tag_152,OUT,FIETSERS,2026-04-30 23:00:00.0,2026-04-30 23:15:00.0,1.0
1107940,Location_Tag_152,OUT,FIETSERS,2026-04-30 23:15:00.0,2026-04-30 23:30:00.0,1.0
1107941,Location_Tag_152,OUT,FIETSERS,2026-04-30 23:30:00.0,2026-04-30 23:45:00.0,0.0

In [12]:
forecaster.run_pipeline(db_path=db_path, cutoff="2026-04-01", forecast_end="2026-04-30", train_days=30)

2026/05/19 21:59:53 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/05/19 21:59:53 INFO mlflow.store.db.utils: Updating database tables
2026/05/19 21:59:53 INFO mlflow.tracking.fluent: Experiment with name 'Forecasting Experiment' does not exist. Creating a new experiment.

query:
    SELECT *
    FROM "traffic_counts"
    WHERE Start_Time >= "2026-03-02 00:00:00"
    AND End_Time <= "2026-04-30 23:59:59";

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000572 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 741
[LightGBM] [Info] Number of data points in the train set: 435, number of used features: 12
[LightGBM] [Info] Start training from score 629.859770
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

2026/05/19 22:00:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/19 22:00:09 WARNING mlflow.lightgbm: Saving the models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Recursive LightGBM MAE: 243.315649598404
Recursive LightGBM RMSE: 456.0450392190779

{'df_daily':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 0      Location_Tag_1 2026-03-02  498.0          0      3         61
 1      Location_Tag_1 2026-03-03  570.0          1      3         62
 2      Location_Tag_1 2026-03-04  605.0          2      3         63
 3      Location_Tag_1 2026-03-05  581.0          3      3         64
 4      Location_Tag_1 2026-03-06  504.0          4      3         65
 ...               ...        ...    ...        ...    ...        ...
 8662  Location_Tag_99 2026-04-26   40.0          6      4        116
 8663  Location_Tag_99 2026-04-27  179.0          0      4        117
 8664  Location_Tag_99 2026-04-28  194.0          1      4        118
 8665  Location_Tag_99 2026-04-29  175.0          2      4        119
 8666  Location_Tag_99 2026-04-30  184.0          3      4        120

       is_weekend  month_sin     month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 0              0   1.000000  6.123234e-17  0.867456  0.497513    NaN    NaN
 1              0   1.000000  6.123234e-17  0.875892  0.482508  498.0    NaN
 2              0   1.000000  6.123234e-17  0.884068  0.467359  570.0    NaN
 3              0   1.000000  6.123234e-17  0.891981  0.452072  605.0    NaN
 4              0   1.000000  6.123234e-17  0.899631  0.436651  581.0    NaN
 ...          ...        ...           ...       ...       ...    ...    ...
 8662           1   0.866025 -5.000000e-01  0.910605 -0.413279   64.0   18.0
 8663           0   0.866025 -5.000000e-01  0.903356 -0.428892   40.0  152.0
 8664           0   0.866025 -5.000000e-01  0.895839 -0.444378  179.0  193.0
 8665           0   0.866025 -5.000000e-01  0.888057 -0.459733  194.0  194.0
 8666           0   0.866025 -5.000000e-01  0.880012 -0.474951  175.0  174.0

       lag_14  lag_28
 0        NaN     NaN
 1        NaN     NaN
 2        NaN     NaN
 3        NaN     NaN
 4        NaN     NaN
 ...      ...     ...
 8662    25.0    23.0
 8663   163.0   152.0
 8664   160.0   159.0
 8665   169.0   155.0
 8666   150.0   160.0

 [8667 rows x 15 columns],
 'df_model':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 28     Location_Tag_1 2026-03-30  339.0          0      3         89
 29     Location_Tag_1 2026-03-31  458.0          1      3         90
 30     Location_Tag_1 2026-04-01  502.0          2      4         91
 31     Location_Tag_1 2026-04-02  408.0          3      4         92
 32     Location_Tag_1 2026-04-03  372.0          4      4         93
 ...               ...        ...    ...        ...    ...        ...
 8662  Location_Tag_99 2026-04-26   40.0          6      4        116
 8663  Location_Tag_99 2026-04-27  179.0          0      4        117
 8664  Location_Tag_99 2026-04-28  194.0          1      4        118
 8665  Location_Tag_99 2026-04-29  175.0          2      4        119
 8666  Location_Tag_99 2026-04-30  184.0          3      4        120

       is_weekend  month_sin     month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 28             0   1.000000  6.123234e-17  0.999250  0.038722  267.0  560.0
 29             0   1.000000  6.123234e-17  0.999769  0.021516  339.0  591.0
 30             0   0.866025 -5.000000e-01  0.999991  0.004304  458.0  309.0
 31             0   0.866025 -5.000000e-01  0.999917 -0.012910  502.0  329.0
 32             0   0.866025 -5.000000e-01  0.999546 -0.030120  408.0  382.0
 ...          ...        ...           ...       ...       ...    ...    ...
 8662           1   0.866025 -5.000000e-01  0.910605 -0.413279   64.0   18.0
 8663           0   0.866025 -5.000000e-01  0.903356 -0.428892   40.0  152.0
 8664           0   0.866025 -5.000000e-01  0.895839 -0.444378  179.0  193.0
 8665           0   0.866025 -5.000000e-01  0.888057 -0.459733  194.0  194.0
 8666           0   0.866025 -5.000000e-01  0.880012 -0.474951  175.0  174.0

       lag_14  lag_28
 28     422.0   498.0
 29     562.0   570.0
 30     649.0   605.0
 31     599.0   581.0
 32     469.0   504.0
 ...      ...     ...
 8662    25.0    23.0
 8663   163.0   152.0
 8664   160.0   159.0
 8665   169.0   155.0
 8666   150.0   160.0

 [4607 rows x 15 columns],
 'train_2Y':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 28     Location_Tag_1 2026-03-30  339.0          0      3         89
 29     Location_Tag_1 2026-03-31  458.0          1      3         90
 30     Location_Tag_1 2026-04-01  502.0          2      4         91
 88    Location_Tag_10 2026-03-30  337.0          0      3         89
 89    Location_Tag_10 2026-03-31  446.0          1      3         90
 ...               ...        ...    ...        ...    ...        ...
 8576  Location_Tag_98 2026-03-31  523.0          1      3         90
 8577  Location_Tag_98 2026-04-01  552.0          2      4         91
 8635  Location_Tag_99 2026-03-30  152.0          0      3         89
 8636  Location_Tag_99 2026-03-31  159.0          1      3         90
 8637  Location_Tag_99 2026-04-01  155.0          2      4         91

       is_weekend  month_sin     month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 28             0   1.000000  6.123234e-17  0.999250  0.038722  267.0  560.0
 29             0   1.000000  6.123234e-17  0.999769  0.021516  339.0  591.0
 30             0   0.866025 -5.000000e-01  0.999991  0.004304  458.0  309.0
 88             0   1.000000  6.123234e-17  0.999250  0.038722  237.0  556.0
 89             0   1.000000  6.123234e-17  0.999769  0.021516  337.0  520.0
 ...          ...        ...           ...       ...       ...    ...    ...
 8576           0   1.000000  6.123234e-17  0.999769  0.021516  414.0  634.0
 8577           0   0.866025 -5.000000e-01  0.999991  0.004304  523.0  390.0
 8635           0   1.000000  6.123234e-17  0.999250  0.038722   23.0  173.0
 8636           0   1.000000  6.123234e-17  0.999769  0.021516  152.0  216.0
 8637           0   0.866025 -5.000000e-01  0.999991  0.004304  159.0  137.0

       lag_14  lag_28
 28     422.0   498.0
 29     562.0   570.0
 30     649.0   605.0
 88     409.0   550.0
 89     524.0   501.0
 ...      ...     ...
 8576   558.0   621.0
 8577   624.0   625.0
 8635   164.0   195.0
 8636   190.0   199.0
 8637   200.0   178.0

 [435 rows x 15 columns],
 'test_actual_2Y':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 31     Location_Tag_1 2026-04-02  408.0          3      4         92
 32     Location_Tag_1 2026-04-03  372.0          4      4         93
 33     Location_Tag_1 2026-04-04  289.0          5      4         94
 34     Location_Tag_1 2026-04-05  216.0          6      4         95
 35     Location_Tag_1 2026-04-06  377.0          0      4         96
 ...               ...        ...    ...        ...    ...        ...
 8662  Location_Tag_99 2026-04-26   40.0          6      4        116
 8663  Location_Tag_99 2026-04-27  179.0          0      4        117
 8664  Location_Tag_99 2026-04-28  194.0          1      4        118
 8665  Location_Tag_99 2026-04-29  175.0          2      4        119
 8666  Location_Tag_99 2026-04-30  184.0          3      4        120

       is_weekend  month_sin  month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 31             0   0.866025       -0.5  0.999917 -0.012910  502.0  329.0
 32             0   0.866025       -0.5  0.999546 -0.030120  408.0  382.0
 33             1   0.866025       -0.5  0.998880 -0.047321  372.0  259.0
 34             1   0.866025       -0.5  0.997917 -0.064508  289.0  267.0
 35             0   0.866025       -0.5  0.996659 -0.081676  216.0  339.0
 ...          ...        ...        ...       ...       ...    ...    ...
 8662           1   0.866025       -0.5  0.910605 -0.413279   64.0   18.0
 8663           0   0.866025       -0.5  0.903356 -0.428892   40.0  152.0
 8664           0   0.866025       -0.5  0.895839 -0.444378  179.0  193.0
 8665           0   0.866025       -0.5  0.888057 -0.459733  194.0  194.0
 8666           0   0.866025       -0.5  0.880012 -0.474951  175.0  174.0

       lag_14  lag_28
 31     599.0   581.0
 32     469.0   504.0
 33     362.0   253.0
 34     433.0   401.0
 35     560.0   543.0
 ...      ...     ...
 8662    25.0    23.0
 8663   163.0   152.0
 8664   160.0   159.0
 8665   169.0   155.0
 8666   150.0   160.0

 [4172 rows x 15 columns],
 'lgbm_model_2Y': LGBMRegressor(learning_rate=0.05, n_estimators=500, random_state=42),
 'eval_df_2Y':                Site_ID Start_Time  dayofweek  month  dayofyear  is_weekend  \
 0       Location_Tag_1 2026-04-02          3      4         92           0
 1      Location_Tag_10 2026-04-02          3      4         92           0
 2     Location_Tag_100 2026-04-02          3      4         92           0
 3     Location_Tag_101 2026-04-02          3      4         92           0
 4     Location_Tag_102 2026-04-02          3      4         92           0
 ...                ...        ...        ...    ...        ...         ...
 4167   Location_Tag_93 2026-04-30          3      4        120           0
 4168   Location_Tag_94 2026-04-30          3      4        120           0
 4169   Location_Tag_97 2026-04-30          3      4        120           0
 4170   Location_Tag_98 2026-04-30          3      4        120           0
 4171   Location_Tag_99 2026-04-30          3      4        120           0

       month_sin  month_cos   doy_sin   doy_cos        lag_1        lag_7  \
 0      0.866025       -0.5  0.999917 -0.012910   502.000000   329.000000
 1      0.866025       -0.5  0.999917 -0.012910   439.000000   274.000000
 2      0.866025       -0.5  0.999917 -0.012910  2115.000000  1728.000000
 3      0.866025       -0.5  0.999917 -0.012910   358.000000   346.000000
 4      0.866025       -0.5  0.999917 -0.012910   316.000000   316.000000
 ...         ...        ...       ...       ...          ...          ...
 4167   0.866025       -0.5  0.880012 -0.474951   291.030584   212.418920
 4168   0.866025       -0.5  0.880012 -0.474951   694.764386   481.844263
 4169   0.866025       -0.5  0.880012 -0.474951   357.775307   330.073463
 4170   0.866025       -0.5  0.880012 -0.474951   378.812739   350.539197
 4171   0.866025       -0.5  0.880012 -0.474951   143.797103   136.571754

            lag_14       lag_28         pred  actual
 0      599.000000   581.000000   549.586605   408.0
 1      656.000000   613.000000   469.668014   383.0
 2     2358.000000  2480.000000  2225.762701  1920.0
 3      382.000000   369.000000   338.399327   233.0
 4      319.000000   352.000000   298.064759   222.0
 ...           ...          ...          ...     ...
 4167   363.362652   384.874865   344.548071   558.0
 4168   763.453245   818.934830   645.126198   883.0
 4169   429.388950   533.176162   341.350168   658.0
 4170   436.187890   527.388815   358.554205   642.0
 4171   202.385641   202.509500   193.639870   184.0

 [4172 rows x 16 columns]}

In [1]:
print("hello")

hello

In [ ]:
import sqlite3
import pandas as pd

db_path = ""

conn = sqlite3.connect(db_path)

query = """
SELECT *
FROM traffic_counts
WHERE Start_Time >= datetime('now', '-3 years');
"""

df = pd.read_sql_query(query, conn)
conn.close()
df

:

:

In [ ]:
import sqlite3
import pandas as pd

db_path = ""

conn = sqlite3.connect(db_path)

query = """
SELECT *
FROM traffic_counts
WHERE Start_Time >= datetime('now', '-3 years');
"""

df = pd.read_sql_query(query, conn)
conn.close()
df

,Site_ID,Direction,Modus,Start_Time,End_Time,Count
0,Location_Tag_1,IN,FIETSERS,2023-05-17 20:30:00.0,2023-05-17 20:45:00.0,3.0
1,Location_Tag_1,IN,FIETSERS,2023-05-17 20:45:00.0,2023-05-17 21:00:00.0,1.0
2,Location_Tag_1,IN,FIETSERS,2023-05-17 21:00:00.0,2023-05-17 21:15:00.0,3.0
3,Location_Tag_1,IN,FIETSERS,2023-05-17 21:15:00.0,2023-05-17 21:30:00.0,2.0
4,Location_Tag_1,IN,FIETSERS,2023-05-17 21:30:00.0,2023-05-17 21:45:00.0,1.0
...,...,...,...,...,...,...
29330645,Location_Tag_152,OUT,FIETSERS,2026-05-13 03:45:00.0,2026-05-13 04:00:00.0,0.0
29330646,Location_Tag_152,OUT,FIETSERS,2026-05-13 04:00:00.0,2026-05-13 04:15:00.0,0.0
29330647,Location_Tag_152,OUT,FIETSERS,2026-05-13 04:15:00.0,2026-05-13 04:30:00.0,0.0
29330648,Location_Tag_152,OUT,FIETSERS,2026-05-13 04:30:00.0,2026-05-13 04:45:00.0,0.0
29330649,Location_Tag_152,OUT,FIETSERS,2026-05-13 04:45:00.0,2026-05-13 05:00:00.0,0.0

In [ ]:
import sqlite3
import pandas as pd

db_path = ""

conn = sqlite3.connect(db_path)

query = """
SELECT * FROM traffic_counts 
WHERE Start_Time >= '2023-09-01 00:00:00' 
AND End_Time <= '2023-09-30 23:59:59';
"""

df = pd.read_sql_query(query, conn)
conn.close()
df

,Site_ID,Direction,Modus,Start_Time,End_Time,Count
0,Location_Tag_1,IN,FIETSERS,2023-09-01 00:00:00.0,2023-09-01 00:15:00.0,0.0
1,Location_Tag_1,IN,FIETSERS,2023-09-01 00:15:00.0,2023-09-01 00:30:00.0,0.0
2,Location_Tag_1,IN,FIETSERS,2023-09-01 00:30:00.0,2023-09-01 00:45:00.0,1.0
3,Location_Tag_1,IN,FIETSERS,2023-09-01 00:45:00.0,2023-09-01 01:00:00.0,0.0
4,Location_Tag_1,IN,FIETSERS,2023-09-01 01:00:00.0,2023-09-01 01:15:00.0,0.0
...,...,...,...,...,...,...
795911,Location_Tag_143,OUT,FIETSERS,2023-09-30 22:30:00.0,2023-09-30 22:45:00.0,14.0
795912,Location_Tag_143,OUT,FIETSERS,2023-09-30 22:45:00.0,2023-09-30 23:00:00.0,21.0
795913,Location_Tag_143,OUT,FIETSERS,2023-09-30 23:00:00.0,2023-09-30 23:15:00.0,20.0
795914,Location_Tag_143,OUT,FIETSERS,2023-09-30 23:15:00.0,2023-09-30 23:30:00.0,15.0
795915,Location_Tag_143,OUT,FIETSERS,2023-09-30 23:30:00.0,2023-09-30 23:45:00.0,16.0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Site_ID     5 non-null      str
 1   Direction   5 non-null      str
 2   Modus       5 non-null      str
 3   Start_Time  5 non-null      str
 4   End_Time    5 non-null      str
 5   Count       5 non-null      float64
dtypes: float64(1), str(5)
memory usage: 702.0 bytes

In [ ]:
forecaster.run_pipeline(
    db_path="",
    cutoff= "2020-10-01",
    forecast_end="2021-04-01"
)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000419 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1855
[LightGBM] [Info] Number of data points in the train set: 9611, number of used features: 13
[LightGBM] [Info] Start training from score 405.653314
Recursive LightGBM MAE: 106.71846047899645
Recursive LightGBM RMSE: 152.56749924972243

{'df_daily':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 0      Location_Tag_1 2019-08-01  495.0          3      8        213
 1      Location_Tag_1 2019-08-02  364.0          4      8        214
 2      Location_Tag_1 2019-08-03  273.0          5      8        215
 3      Location_Tag_1 2019-08-04  424.0          6      8        216
 4      Location_Tag_1 2019-08-05  455.0          0      8        217
 ...               ...        ...    ...        ...    ...        ...
 15581  Location_Tag_9 2021-04-26  423.0          0      4        116
 15582  Location_Tag_9 2021-04-27  456.0          1      4        117
 15583  Location_Tag_9 2021-04-28  496.0          2      4        118
 15584  Location_Tag_9 2021-04-29  322.0          3      4        119
 15585  Location_Tag_9 2021-04-30  337.0          4      4        120

        is_weekend  month_sin  month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 0               0  -0.866025       -0.5 -0.501242 -0.865307    NaN    NaN
 1               0  -0.866025       -0.5 -0.516062 -0.856551  495.0    NaN
 2               1  -0.866025       -0.5 -0.530730 -0.847541  364.0    NaN
 3               1  -0.866025       -0.5 -0.545240 -0.838280  273.0    NaN
 4               0  -0.866025       -0.5 -0.559589 -0.828770  424.0    NaN
 ...           ...        ...        ...       ...       ...    ...    ...
 15581           0   0.866025       -0.5  0.910605 -0.413279  226.0  330.0
 15582           0   0.866025       -0.5  0.903356 -0.428892  423.0  444.0
 15583           0   0.866025       -0.5  0.895839 -0.444378  456.0  452.0
 15584           0   0.866025       -0.5  0.888057 -0.459733  496.0  372.0
 15585           0   0.866025       -0.5  0.880012 -0.474951  322.0  395.0

        lag_14  lag_28
 0         NaN     NaN
 1         NaN     NaN
 2         NaN     NaN
 3         NaN     NaN
 4         NaN     NaN
 ...       ...     ...
 15581   159.0   394.0
 15582   219.0   407.0
 15583   201.0   432.0
 15584   197.0   361.0
 15585   253.0   208.0

 [15586 rows x 15 columns],
 'df_model':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 28     Location_Tag_1 2019-08-29  499.0          3      8        241
 29     Location_Tag_1 2019-08-30  483.0          4      8        242
 30     Location_Tag_1 2019-08-31  292.0          5      8        243
 31     Location_Tag_1 2019-09-01  818.0          6      9        244
 32     Location_Tag_1 2019-09-02  537.0          0      9        245
 ...               ...        ...    ...        ...    ...        ...
 15581  Location_Tag_9 2021-04-26  423.0          0      4        116
 15582  Location_Tag_9 2021-04-27  456.0          1      4        117
 15583  Location_Tag_9 2021-04-28  496.0          2      4        118
 15584  Location_Tag_9 2021-04-29  322.0          3      4        119
 15585  Location_Tag_9 2021-04-30  337.0          4      4        120

        is_weekend  month_sin     month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 28              0  -0.866025 -5.000000e-01 -0.845249 -0.534373  472.0  501.0
 29              0  -0.866025 -5.000000e-01 -0.854322 -0.519744  499.0  431.0
 30              1  -0.866025 -5.000000e-01 -0.863142 -0.504961  483.0  263.0
 31              1  -1.000000 -1.836970e-16 -0.871706 -0.490029  292.0  382.0
 32              0  -1.000000 -1.836970e-16 -0.880012 -0.474951  818.0  546.0
 ...           ...        ...           ...       ...       ...    ...    ...
 15581           0   0.866025 -5.000000e-01  0.910605 -0.413279  226.0  330.0
 15582           0   0.866025 -5.000000e-01  0.903356 -0.428892  423.0  444.0
 15583           0   0.866025 -5.000000e-01  0.895839 -0.444378  456.0  452.0
 15584           0   0.866025 -5.000000e-01  0.888057 -0.459733  496.0  372.0
 15585           0   0.866025 -5.000000e-01  0.880012 -0.474951  322.0  395.0

        lag_14  lag_28
 28      237.0   495.0
 29      291.0   364.0
 30       96.0   273.0
 31      151.0   424.0
 32      363.0   455.0
 ...       ...     ...
 15581   159.0   394.0
 15582   219.0   407.0
 15583   201.0   432.0
 15584   197.0   361.0
 15585   253.0   208.0

 [14886 rows x 15 columns],
 'train_2Y':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 28     Location_Tag_1 2019-08-29  499.0          3      8        241
 29     Location_Tag_1 2019-08-30  483.0          4      8        242
 30     Location_Tag_1 2019-08-31  292.0          5      8        243
 31     Location_Tag_1 2019-09-01  818.0          6      9        244
 32     Location_Tag_1 2019-09-02  537.0          0      9        245
 ...               ...        ...    ...        ...    ...        ...
 15370  Location_Tag_9 2020-09-27  129.0          6      9        271
 15371  Location_Tag_9 2020-09-28  230.0          0      9        272
 15372  Location_Tag_9 2020-09-29  445.0          1      9        273
 15373  Location_Tag_9 2020-09-30  472.0          2      9        274
 15374  Location_Tag_9 2020-10-01  326.0          3     10        275

        is_weekend  month_sin     month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 28              0  -0.866025 -5.000000e-01 -0.845249 -0.534373  472.0  501.0
 29              0  -0.866025 -5.000000e-01 -0.854322 -0.519744  499.0  431.0
 30              1  -0.866025 -5.000000e-01 -0.863142 -0.504961  483.0  263.0
 31              1  -1.000000 -1.836970e-16 -0.871706 -0.490029  292.0  382.0
 32              0  -1.000000 -1.836970e-16 -0.880012 -0.474951  818.0  546.0
 ...           ...        ...           ...       ...       ...    ...    ...
 15370           1  -1.000000 -1.836970e-16 -0.998880 -0.047321  112.0  404.0
 15371           0  -1.000000 -1.836970e-16 -0.999546 -0.030120  129.0  606.0
 15372           0  -1.000000 -1.836970e-16 -0.999917 -0.012910  230.0  641.0
 15373           0  -1.000000 -1.836970e-16 -0.999991  0.004304  445.0  523.0
 15374           0  -0.866025  5.000000e-01 -0.999769  0.021516  472.0  406.0

        lag_14  lag_28
 28      237.0   495.0
 29      291.0   364.0
 30       96.0   273.0
 31      151.0   424.0
 32      363.0   455.0
 ...       ...     ...
 15370   434.0   148.0
 15371   642.0   322.0
 15372   600.0   589.0
 15373   642.0   636.0
 15374   541.0   402.0

 [9611 rows x 15 columns],
 'test_actual_2Y':               Site_ID Start_Time  Count  dayofweek  month  dayofyear  \
 428    Location_Tag_1 2020-10-02  284.0          4     10        276
 429    Location_Tag_1 2020-10-03  137.0          5     10        277
 430    Location_Tag_1 2020-10-04  176.0          6     10        278
 431    Location_Tag_1 2020-10-05  272.0          0     10        279
 432    Location_Tag_1 2020-10-06  365.0          1     10        280
 ...               ...        ...    ...        ...    ...        ...
 15552  Location_Tag_9 2021-03-28  186.0          6      3         87
 15553  Location_Tag_9 2021-03-29  394.0          0      3         88
 15554  Location_Tag_9 2021-03-30  407.0          1      3         89
 15555  Location_Tag_9 2021-03-31  432.0          2      3         90
 15556  Location_Tag_9 2021-04-01  361.0          3      4         91

        is_weekend  month_sin     month_cos   doy_sin   doy_cos  lag_1  lag_7  \
 428             0  -0.866025  5.000000e-01 -0.999250  0.038722  295.0  281.0
 429             1  -0.866025  5.000000e-01 -0.998435  0.055917  284.0   80.0
 430             1  -0.866025  5.000000e-01 -0.997325  0.073095  137.0  168.0
 431             0  -0.866025  5.000000e-01 -0.995919  0.090252  176.0  258.0
 432             0  -0.866025  5.000000e-01 -0.994218  0.107381  272.0  505.0
 ...           ...        ...           ...       ...       ...    ...    ...
 15552           1   1.000000  6.123234e-17  0.997325  0.073095  131.0  148.0
 15553           0   1.000000  6.123234e-17  0.998435  0.055917  186.0  313.0
 15554           0   1.000000  6.123234e-17  0.999250  0.038722  394.0  374.0
 15555           0   1.000000  6.123234e-17  0.999769  0.021516  407.0  399.0
 15556           0   0.866025 -5.000000e-01  0.999991  0.004304  432.0  325.0

        lag_14  lag_28
 428     603.0   442.0
 429     387.0   329.0
 430     777.0   594.0
 431     596.0   582.0
 432     645.0   616.0
 ...       ...     ...
 15552    89.0   258.0
 15553   257.0   343.0
 15554   222.0   451.0
 15555   246.0   422.0
 15556   289.0   210.0

 [4550 rows x 15 columns],
 'lgbm_model_2Y': LGBMRegressor(learning_rate=0.05, n_estimators=500, random_state=42),
 'eval_df_2Y':               Site_ID Start_Time  dayofweek  month  dayofyear  is_weekend  \
 0      Location_Tag_1 2020-10-02          4     10        276           0
 1     Location_Tag_10 2020-10-02          4     10        276           0
 2     Location_Tag_11 2020-10-02          4     10        276           0
 3     Location_Tag_12 2020-10-02          4     10        276           0
 4     Location_Tag_13 2020-10-02          4     10        276           0
 ...               ...        ...        ...    ...        ...         ...
 4545   Location_Tag_5 2021-04-01          3      4         91           0
 4546   Location_Tag_6 2021-04-01          3      4         91           0
 4547   Location_Tag_7 2021-04-01          3      4         91           0
 4548   Location_Tag_8 2021-04-01          3      4         91           0
 4549   Location_Tag_9 2021-04-01          3      4         91           0

       month_sin  month_cos   doy_sin   doy_cos       lag_1       lag_7  \
 0     -0.866025        0.5 -0.999250  0.038722  295.000000  281.000000
 1     -0.866025        0.5 -0.999250  0.038722  173.000000  212.000000
 2     -0.866025        0.5 -0.999250  0.038722  232.000000  274.000000
 3     -0.866025        0.5 -0.999250  0.038722  252.000000  228.000000
 4     -0.866025        0.5 -0.999250  0.038722  676.000000  597.000000
 ...         ...        ...       ...       ...         ...         ...
 4545   0.866025       -0.5  0.999991  0.004304   96.848991  134.700476
 4546   0.866025       -0.5  0.999991  0.004304  201.415713  287.061845
 4547   0.866025       -0.5  0.999991  0.004304  191.545659  234.775376
 4548   0.866025       -0.5  0.999991  0.004304  170.701544  212.404664
 4549   0.866025       -0.5  0.999991  0.004304  218.278445  303.562889

            lag_14      lag_28        pred  actual
 0      603.000000  442.000000  347.952145   284.0
 1      403.000000  367.000000  242.120192   143.0
 2      596.000000  538.000000  357.514684   237.0
 3      467.000000  301.000000  294.586187   177.0
 4     1047.000000  903.000000  733.016804   660.0
 ...           ...         ...         ...     ...
 4545   134.768768   95.008877  140.841782   203.0
 4546   295.185342  285.432148  245.949068   332.0
 4547   273.073695  265.042878  228.602047   297.0
 4548   250.187193  246.378808  201.965801   258.0
 4549   296.788775  290.094134  278.219471   361.0

 [4550 rows x 16 columns]}

In [2]:
import pandas as pd

In [5]:
pd.Timestamp("2025-05-01").strftime("%Y-%m-%d") + " 00:00:00"

'2025-05-01 00:00:00'

In [14]:
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")

mlflow.set_experiment("my-experiment")

with mlflow.start_run():
    mlflow.log_param("test_param", "hello")
    mlflow.log_metric("test_metric", 123)

2026/05/20 12:51:49 INFO mlflow.tracking.fluent: Experiment with name 'my-experiment' does not exist. Creating a new experiment.

🏃 View run fun-crab-699 at: http://127.0.0.1:5000/#/experiments/1/runs/4ee7d2eb93df404ea03362fa0fabcb5d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1